boards/cats_rev1Pro/Core/Inc/config/globals.h, boards/cats_rev1Pro/Core/Inc/control/sensor_elimination.h, boards/cats_rev1Pro/Core/Inc/drivers/spi.h, boards/cats_rev1Pro/Core/Inc/util/recorder.h, boards/cats_rev1Pro/Core/Inc/util/types.h, boards/cats_rev1Pro/Core/Src/control/kalman_filter.c, boards/cats_rev1Pro/Core/Src/control/sensor_elimination.c, boards/cats_rev1Pro/Core/Src/drivers/spi.c, boards/cats_rev1Pro/Core/Src/tasks/task_imu_read.c, boards/cats_rev1Pro/Core/Src/tasks/task_init.c, boards/cats_rev1Pro/Core/Src/tasks/task_recorder.c, boards/cats_rev1Pro/Core/Src/tasks/task_state_est.c, boards/cats_rev1Pro/Core/Src/util/recorder.c
Filter improvements regarding 100g Accel + Magneto Bugfix + Magneto Logging
1. Implemented, that 100 G accelerometer data is only injecteded if
a. We are above 32G acceleration
b. both other imus are nonfunctional
2. Added initialisation of the magnetometer in the init task
3. Added Magnetometer logging and also added it to the cats-logging repo
=> Kf imu fix

README.md
=> Added source of cli and contribution section to the README

boards/cats_rev1Pro/src/cli/cli.c, boards/cats_rev1Pro/src/control/data_processing.c, boards/cats_rev1Pro/src/control/data_processing.h, boards/cats_rev1Pro/src/drivers/w25q.c, boards/cats_rev1Pro/src/drivers/w25q.h, boards/cats_rev1Pro/src/lfs/lfs_custom.c, boards/cats_rev1Pro/src/util/fifo.c, boards/cats_rev1Pro/src/util/fifo.h, boards/cats_rev1Pro/src/util/reader.c
Also adds the log parser! <3
Closes #32
=> Fixes the LFS problems.

boards/cats_rev1Pro/src/control/data_processing.c, boards/cats_rev1Pro/src/control/data_processing.h, boards/cats_rev1Pro/src/tasks/task_state_est.c
This pull request fixes #66. I haven't managed to build the codebase myself yet, because I'm getting some errors with CMake, and I don't have enough time to resolve this problem until the weekend. So there could be some stupid compilation error. And the diff text looks weird, I don't know why.
=> Improved median filtering algorithm

boards/cats_rev1Pro/src/cli/cli_commands.c, boards/cats_rev1Pro/src/config/globals.c, boards/cats_rev1Pro/src/flash/reader.c, boards/cats_rev1Pro/src/flash/reader.h, boards/cats_rev1Pro/src/tasks/task_recorder.c
1) Remove "rec_erase" command
2) Bump up code version to 2.1.0+
=> Small fixes

boards/cats_rev1Pro/src/tasks/task_init.c, boards/cats_rev1Pro/src/tasks/task_peripherals.c
Fixed the issue seen by HELVETIA.
=> Made the Timers more robust on initialization.

boards/cats_rev1Pro/src/cli/cli_commands.c
Example:
'flight_dump -1' will dump the log of the last flight.
The indexing also works with -2, -3, etc.
All log output functions support this feature:
- flight_dump
- flight_parse
- stats
Other fixes:
- Initialize flight_counter back to 0 in 'lfs_format' command.
Closes #117.
=> Add support for tail indexing.

boards/cats_rev1Pro/src/cli/cli_commands.c, boards/cats_rev1Pro/src/util/types.h
=> Add more information to 'config' CLI command.

boards/cats_rev1Pro/src/cli/settings.c
=> Change the minimum output RF power to 16dBm

boards/cats_rev1Pro/src/cli/cli_commands.c, boards/cats_rev1Pro/src/cli/settings.c, boards/cats_rev1Pro/src/cli/settings.h, boards/cats_rev1Pro/src/config/cats_config.c, boards/cats_rev1Pro/src/config/cats_config.h, boards/cats_rev1Pro/src/init/tasks.c, boards/cats_rev1Pro/src/util/enum_str_maps.c, boards/cats_rev1Pro/src/util/enum_str_maps.h
=> Remove boot state

boards/cats_rev1Pro/src/cli/settings.c, boards/cats_rev1Pro/src/cli/settings.h, boards/cats_rev1Pro/src/config/cats_config.c, boards/cats_rev1Pro/src/tasks/task_telemetry.c, boards/cats_rev1Pro/src/util/enum_str_maps.c, boards/cats_rev1Pro/src/util/enum_str_maps.h, boards/cats_rev1Pro/src/util/types.h
=> Remove transmission direction

boards/cats_rev1Pro/src/tasks/task_telemetry.c, boards/cats_rev1Pro/src/util/telemetry_reg.h
=> Add amplifier temperature information

firmware/src/util/error_handler.h
=> Removed USB Detect from error handler.

firmware/src/cli/cli_commands.c, firmware/src/cli/settings.c, firmware/src/config/cats_config.c, firmware/src/config/cats_config.h, firmware/src/control/flight_phases.c, firmware/src/control/flight_phases.h, firmware/src/flash/reader.c, firmware/src/util/types.h
Closes #158
Other changes:
- Improvements in reading the stats file
- Check if config versions match before printing
=> Make liftoff detection height configurable.

firmware/src/control/flight_phases.h, firmware/src/flash/reader.c, firmware/src/flash/recorder.h, firmware/src/tasks/task_telemetry.c, firmware/src/util/gnss.h
=> Include absolute time info

firmware/src/flash/reader.c, firmware/src/flash/recorder.h, firmware/src/init/config.c, firmware/src/tasks/task_flight_fsm.c, firmware/src/tasks/task_peripherals.c, firmware/src/util/actions.h, firmware/src/util/log.c, firmware/src/util/types.h
=> Add support for logging of action types and their arguments

firmware/src/control/kalman_filter.c, firmware/src/control/kalman_filter.h, firmware/src/tasks/task_state_est.c
Covers now better the case if the IMU is eliminated or if the angle of attack is large.
=> Kalman Filter improvements

.github/workflows/build.yml
=> Add build CI Job

firmware/src/cli/cli_commands.cpp, firmware/src/util/enum_str_maps.cpp
=> Fix flight state printing

firmware/src/config/cats_config.cpp, firmware/target/VEGA/STM32F411CCUX_FLASH.ld
=> Remove EEPROM config support.

firmware/src/cli/cli_commands.cpp, firmware/src/config/globals.h, firmware/src/flash/reader.cpp, firmware/src/flash/recorder.cpp, firmware/src/flash/recorder.h, firmware/src/tasks/task_health_monitor.cpp, firmware/src/tasks/task_recorder.cpp, firmware/src/util/battery.cpp, firmware/src/util/battery.h
=> Add Voltage Logging

firmware/src/tasks/task_preprocessing.h, firmware/src/tasks/task_sensor_read.h
=> Make only necessary data public in sensor read and preprocessing

firmware/src/cli/cli_commands.cpp, firmware/src/control/calibration.cpp, firmware/src/control/calibration.h, firmware/src/flash/reader.cpp, firmware/src/flash/recorder.cpp, firmware/src/flash/recorder.h, firmware/src/tasks/task_preprocessing.cpp, firmware/src/tasks/task_preprocessing.h, firmware/src/tasks/task_recorder.cpp, firmware/src/tasks/task_sensor_read.cpp, firmware/src/tasks/task_sensor_read.h, firmware/src/util/types.h, firmware/target/VEGA/target.cpp, firmware/target/VEGA/target.h
Removed IMU and Magnetometer support. Cleaned up calibration. Cleaned up target file.
=> Remove Dead Code of the Control Architecture

firmware/src/cli/settings.cpp, firmware/src/config/cats_config.cpp, firmware/src/config/cats_config.h, firmware/src/config/globals.cpp, firmware/src/main.cpp, firmware/src/tasks/task_buzzer.cpp
=> Add buzzer volume to cli

firmware/src/cli/settings.cpp, firmware/src/cli/settings.h, firmware/src/config/cats_config.cpp, firmware/src/config/cats_config.h, firmware/src/main.cpp, firmware/src/util/battery.cpp, firmware/src/util/battery.h, firmware/src/util/enum_str_maps.cpp, firmware/src/util/enum_str_maps.h, firmware/src/util/types.h
=> Add battery type information to CLI and config

firmware/src/flash/reader.cpp, firmware/src/tasks/task_recorder.cpp
Tested with Simulation and USB MSC branch:
=> Save code version to flight log

firmware/src/cli/cli_commands.cpp, firmware/src/cli/settings.cpp, firmware/src/tasks/task_telemetry.cpp, firmware/src/tasks/task_telemetry.hpp, firmware/src/util/types.hpp
=> Extend link and test phrases to 16 chars.

firmware/src/config/cats_config.cpp
=> Add delays to default pyro configuration

flight_computer/src/main.cpp, flight_computer/src/target/VEGA/target.cpp, flight_computer/src/target/VEGA/target.h
Add testing button in the software.
Only on boot up the button is checked, afterwards it has no functionality.
=> Add testing button

ground_station/lib/MadgwickAHRS/src/MadgwickAHRS.cpp, ground_station/src/config.cpp, ground_station/src/config.hpp, ground_station/src/hmi/hmi.cpp, ground_station/src/hmi/hmi.hpp, ground_station/src/hmi/window.cpp, ground_station/src/hmi/window.hpp, ground_station/src/main.cpp, ground_station/src/navigation.cpp, ground_station/src/navigation.hpp, ground_station/src/systemParser.cpp, ground_station/src/systemParser.hpp
Implemented the sensor panel, showing the IMU and GNSS Data.
In the sensor panel, the magnetometer can now be calibrated which is saved to the flash.
The default home/rocket location is set to 0.
closes #302
closes #290
=> [GS] Sensor panel

flight_computer/platformio.ini, flight_computer/pre_config.py, flight_computer/src/cli/cli_commands.cpp, flight_computer/src/cli/settings.cpp, flight_computer/src/flash/reader.cpp, flight_computer/src/flash/reader.hpp, flight_computer/src/flash/recorder.hpp, flight_computer/src/init/system.cpp, flight_computer/src/tasks/task_recorder.cpp, flight_computer/src/usb/msc/emfat_file.c, flight_computer/src/usb/msc/emfat_file.h, flight_computer/src/usb/msc_disk.c
=> [FC] Expose flight stats through MSC

ground_station/src/main.cpp
=> [GS] Use both links in single mode for the rocket location

flight_computer/src/tasks/task_preprocessing.cpp, flight_computer/src/tasks/task_preprocessing.hpp, flight_computer/src/tasks/task_telemetry.cpp, flight_computer/src/util/error_handler.hpp, ground_station/src/hmi/window.cpp
A Calibration Faulty Error is now sent to the GS if the flight computer is rotated after being calibrated
closes #278
=> Added Calibration Faulty Error

flight_computer/CMakeLists.txt, flight_computer/platformio.ini, flight_computer/src/FreeRTOSConfig.h, flight_computer/src/cli/cli_commands.cpp, flight_computer/src/config/globals.hpp, flight_computer/src/util/debug.cpp, flight_computer/src/util/log.cpp, flight_computer/src/util/log.h
Closes #361
- [/] Copyright notice for new files
- [/] `#pragma once` directive for new header files
=> Rename CATS_DEBUG to CATS_DEV to avoid confusion with debug build

.github/workflows/merge-criteria.yml
=> Enable manual triggering of Merge Criteria workflow

.github/workflows/merge-criteria.yml, ground_station/src/config.cpp, ground_station/src/config.hpp, ground_station/src/hmi/settings.cpp, ground_station/src/hmi/settings.hpp, ground_station/src/hmi/window.cpp, ground_station/src/hmi/window.hpp, ground_station/src/systemParser.cpp, ground_station/src/systemParser.hpp, ground_station/src/utils.hpp
This patch adds support for imperial units on the Ground Station.
Closes #375.
=> [GS] Add Imperial Units

.github/workflows/merge-criteria.yml
=> Artifact upgrade

telemetry/src/Gps/Gps.cpp
Put the UBLOX module into high acceleration mode (4g airborne).
- [ x] Feature tested manually [Mandatory]
- [ na] Simulation flight performed [Optional]
- [ na] Drone flight performed [Optional]
- [ na] Copyright notice for new files
- [ na] `#pragma once` directive for new header files
- [na ] Simulation flight performed [Mandatory]
- [ na] Drone flight performed [Optional]
- [ na] Version number incremented [Mandatory]
- [ na] Develop and debug flag disabled [Mandatory]
Closes #352
=> [Telemetry] Change UBLOX config

.github/workflows/merge-criteria.yml
=> Update all actions

ground_station/platformio.ini
=> Bump to 1.1.4
